FROM gophish/gophish:latest

USER root
COPY config.json /opt/gophish/config.json
RUN chmod +x /opt/gophish/run-remote.sh || true \
    && mkdir -p /opt/gophish/data \
    && chown -R app:app /opt/gophish/data

EXPOSE 3333

ENTRYPOINT ["/opt/gophish/docker/run.sh"]
