import { ReactNode, useMemo, useState } from 'react'

export type DataColumn<T> = { key: string; label: string; value?: (row: T) => string | number; render: (row: T) => ReactNode; className?: string }

export function DataTable<T>({ rows, columns, searchKeys = [], emptyText, expanded, pageSize = 10 }: { rows: T[]; columns: DataColumn<T>[]; searchKeys?: ((row: T) => string)[]; emptyText: string; expanded?: (row: T) => ReactNode; pageSize?: number }) {
  const [search, setSearch] = useState(''); const [sort, setSort] = useState<string | null>(null); const [descending, setDescending] = useState(false); const [page, setPage] = useState(0)
  const filtered = useMemo(() => rows.filter(row => !search || searchKeys.some(key => key(row).toLowerCase().includes(search.toLowerCase()))).sort((left, right) => { if (!sort) return 0; const column = columns.find(item => item.key === sort); if (!column?.value) return 0; return String(column.value(left)).localeCompare(String(column.value(right)), undefined, { numeric: true }) * (descending ? -1 : 1) }), [rows, search, searchKeys, sort, descending, columns])
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const currentPage = Math.min(page, totalPages - 1); const visible = filtered.slice(currentPage * pageSize, (currentPage + 1) * pageSize); const getRowId = (row: T) => { const item = row as { id?: string | number; recipientId?: string | number }; return item.id ?? item.recipientId ?? JSON.stringify(row) }
  const toggleSort = (key: string) => { setPage(0); setDescending(sort === key ? !descending : false); setSort(key) }
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-4"><input value={search} onChange={event => { setSearch(event.target.value); setPage(0) }} placeholder="Buscar…" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none ring-[#d95d39] focus:ring-2" /></div><div className="max-h-[34rem] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 z-10 bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr>{columns.map(column => <th key={column.key} className={`p-3 ${column.className || ''}`}><button type="button" onClick={() => toggleSort(column.key)} className="font-bold hover:text-[#d95d39]">{column.label}{sort === column.key ? descending ? ' ↓' : ' ↑' : ''}</button></th>)}</tr></thead><tbody>{visible.map(row => <><tr key={getRowId(row)} className="border-t border-slate-100 align-top hover:bg-orange-50/30">{columns.map(column => <td key={column.key} className={`p-3 ${column.className || ''}`}>{column.render(row)}</td>)}</tr>{expanded ? <tr key={`${getRowId(row)}-expanded`} className="border-t border-slate-100 bg-slate-50/60"><td colSpan={columns.length} className="p-4">{expanded(row)}</td></tr> : null}</>)}</tbody></table>{!visible.length && <p className="p-10 text-center text-sm text-slate-500">{emptyText}</p>}</div><div className="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-sm text-slate-500"><span>{filtered.length} resultados · {currentPage + 1}/{totalPages}</span><div className="flex gap-2"><button type="button" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)} className="rounded border border-slate-200 px-3 py-1 disabled:opacity-40">Anterior</button><button type="button" disabled={currentPage + 1 >= totalPages} onClick={() => setPage(currentPage + 1)} className="rounded border border-slate-200 px-3 py-1 disabled:opacity-40">Siguiente</button></div></div></div>
}
