import type { CampaignEvent, CampaignStats } from '../api'

const eventLabels: Record<string, string> = { EMAIL_SENT: 'Email enviado', EMAIL_DELIVERED: 'Email entregado', EMAIL_OPENED: 'Email abierto', LINK_CLICKED: 'Enlace pulsado', LANDING_VIEWED: 'Landing vista', FORM_SUBMITTED: 'Formulario enviado', EMAIL_REPORTED: 'Email reportado', TRAINING_VIEWED: 'Formación vista', TRAINING_COMPLETED: 'Formación completada' }

export function Funnel({ stats }: { stats: CampaignStats }) { const rows = [['Enviados', stats.totalSent], ['Abiertos', stats.totalOpened], ['Clics', stats.totalClicked], ['Envíos', stats.totalSubmitted], ['Formación', stats.totalTrainingCompleted]]; const top = Math.max(stats.totalSent, 1); return <section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#d95d39]">Embudo de simulación</p><h2 className="mt-1 font-serif text-2xl">Atención → aprendizaje</h2><div className="mt-6 grid gap-3">{rows.map(([label, value], index) => <div key={String(label)}><div className="mb-1 flex justify-between text-sm"><span>{label}</span><b>{value}</b></div><div className="h-8 overflow-hidden rounded-r-full bg-slate-100"><div className="h-full rounded-r-full bg-[#d95d39] transition-all" style={{ width: `${Math.max(6, Number(value) * 100 / top)}%`, opacity: 1 - index * .1 }} /></div></div>)}</div></section> }

export function CampaignStepper({ status }: { status: string }) { const states = ['DRAFT', 'SCHEDULED', 'RUNNING', 'COMPLETED']; const current = Math.max(0, states.indexOf(status)); return <div className="flex items-center gap-1 overflow-x-auto py-2">{states.map((state, index) => <div key={state} className="flex items-center gap-1"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs font-bold ${index <= current ? 'bg-[#d95d39] text-white' : 'bg-slate-200 text-slate-500'}`}>{index + 1}</span><span className={`text-xs font-bold ${index <= current ? 'text-[#102a43]' : 'text-slate-400'}`}>{state === 'DRAFT' ? 'Borrador' : state === 'SCHEDULED' ? 'Agendada' : state === 'RUNNING' ? 'Enviada' : 'Resultados'}</span>{index < states.length - 1 ? <span className="mx-1 h-px w-6 bg-slate-200" /> : null}</div>)}</div> }

export function EventTimeline({ events }: { events: CampaignEvent[] }) { if (!events.length) return <p className="text-sm text-slate-500">Sin eventos aún.</p>; return <ol className="grid gap-3">{events.map(event => <li key={event.id} className="flex gap-3"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-[#d95d39]" /><div><p className="text-sm font-semibold">{eventLabels[event.type] || event.type}</p><p className="text-xs text-slate-500">{new Date(event.eventTime).toLocaleString('es-MX')}</p></div></li>)}</ol> }
