import { Link } from 'react-router'
import { useQuery } from '@tanstack/react-query'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../api'
import type { Dashboard as DashboardData, TrendPoint } from '../api'
import { Button, PageTitle, StatCard } from '../components/ui'
import { Funnel } from '../components/OperationsVisuals'
import { ErrorState, Skeleton } from '../components/States'

export default function Dashboard() {
  const dashboard = useQuery<DashboardData>({ queryKey: ['dashboard'], queryFn: () => api.get('/dashboard').then(response => response.data) })
  const trend = useQuery<TrendPoint[]>({ queryKey: ['trend'], queryFn: () => api.get('/analytics/trend').then(response => response.data) })
  if (dashboard.isLoading) return <Skeleton />
  if (dashboard.error || !dashboard.data) return <ErrorState error={dashboard.error} retry={() => dashboard.refetch()} />
  const data = dashboard.data
  const rate = (value: number) => data.totalSent ? Math.round(value * 10000 / data.totalSent) / 100 : 0
  const stats = { totalSent: data.totalSent, totalOpened: data.totalOpened, totalClicked: data.totalClicked, totalSubmitted: data.totalSubmitted, totalReported: data.totalReported, totalTrainingViewed: data.totalTrainingViewed, totalTrainingCompleted: data.totalTrainingCompleted, openRate: rate(data.totalOpened), clickRate: rate(data.totalClicked), submitRate: rate(data.totalSubmitted), trainingRate: rate(data.totalTrainingCompleted) }
  return <><PageTitle eyebrow="Resumen" title="Panorama de riesgo" action={<Link to="/campaigns"><Button>Nueva campaña</Button></Link>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Campañas activas" value={data.activeCampaigns} note={`${data.totalCampaigns} creadas`} /><StatCard label="Emails enviados" value={data.totalSent} note="Destinatarios alcanzados" /><StatCard label="Envíos de formulario" value={data.totalSubmitted} note={`${data.totalSent ? Math.round(data.totalSubmitted * 100 / data.totalSent) : 0}% de enviados`} /><StatCard label="Formación completada" value={data.totalTrainingCompleted} note="Personas que cerraron ciclo" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_1fr]"><Funnel stats={stats} /><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#d95d39]">Tendencia</p><h2 className="mt-1 font-serif text-2xl">Caídas y formación por día</h2>{trend.isLoading ? <div className="mt-6 h-64 animate-pulse rounded-xl bg-slate-100" /> : trend.error ? <p className="mt-6 text-sm text-red-700">No se pudo cargar tendencia.</p> : <div className="mt-6 h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend.data}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tick={{ fontSize: 11 }} /><Tooltip /><Line type="monotone" dataKey="submissions" name="Envíos" stroke="#d95d39" strokeWidth={3} /><Line type="monotone" dataKey="trainingCompleted" name="Formación" stroke="#102a43" strokeWidth={3} /></LineChart></ResponsiveContainer></div>}</section></div><section className="mt-6 rounded-2xl bg-[#102a43] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#f2a27e]">Campañas recientes</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{data.recentCampaigns.length ? data.recentCampaigns.map(campaign => <Link key={campaign.id} to={`/campaigns/${campaign.id}`} className="border-b border-white/10 pb-3 last:border-0"><div className="flex justify-between gap-3"><span className="font-semibold">{campaign.name}</span><span className="text-xs text-[#f2a27e]">{campaign.status}</span></div><p className="mt-1 text-xs text-slate-400">{new Date(campaign.createdAt).toLocaleDateString('es-MX')}</p></Link>) : <p className="text-slate-400">Aún no hay campañas.</p>}</div></section></>
}
